name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/setup_env.sh
      - run: mkdir build && cd build && cmake .. && make
      - run: ./scripts/run_tests.sh
